### ISSUE TITLE
CSIP Profile: cannot access https://dilcis.eu/XML/METS/CSIPExtensionMETS/DILCISExtensionMETS.xsd

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-CSIP#529]
CSIP, SIP, AIP,DIP METS Profile(s)
Error 404 on trying to access one of the XML Schemas for CSIP METS profile:
https://dilcis.eu/XML/METS/CSIPExtensionMETS/DILCISExtensionMETS.xsd

**Comment by elbre** [comment]
Is there any time frame when will be URL links to schemas published?

**Comment by karinbredenberg** [comment]
Update on the way.

**Comment by karinbredenberg** [comment]
Fixed with PR #581

**Comment by shsdev** [comment]
Is this fixed?
Because I still cannot access the XSD under this link: https://dilcis.eu/XML/METS/CSIPExtensionMETS/DILCISExtensionMETS.xsd

**Comment by karinbredenberg** [comment]
@shsdev its this link to the profile the namespace for it is the one you gave: [http://earkcsip.dilcis.eu/schema/DILCISExtensionMETS.xsd](http://earkcsip.dilcis.eu/schema/DILCISExtensionMETS.xsd )
